name: Fetch NSE Play

on:
  schedule:
   - cron: "30 9 * * *" # Every 5 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run IPO Data Fetcher
      run: python rsi_sender.py
      continue-on-error: true

    - name: Run IPO Data Fetcher
      run: python rsi_high.py
      continue-on-error: true

