name: Fetch NSE Play

on:
  schedule:
    - cron: "0 */5 * * *"  # Every 5 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO: ${{ secrets.EMAIL_TO }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install playwright beautifulsoup4
        playwright install --with-deps firefox

    - name: Run IPO Data Fetcher
      run: python mobil_tric.py
      continue-on-error: true

    - name: Run Press Release Fetcher
      run: python press_release.py
      continue-on-error: true

    - name: Run Financial Results Fetcher
      run: python financial_sender.py
      continue-on-error: true

    - name: Run Event Calendar Fetcher
      run: python event_calendar.py
      continue-on-error: true

    - name: Run Bulk Deals Fetcher
      run: python bulk_deals.py
      continue-on-error: true

    - name: Run Market Data Fetcher
      run: python market_data.py
      continue-on-error: true

    - name: Run BSE Notices Fetcher
      run: python bse_notices.py
      continue-on-error: true

    - name: Run Insider Trading Fetcher
      run: python insider_trading.py
      continue-on-error: true

    - name: Run Analyst Recommendations Fetcher
      run: python analyst_recommendations.py
      continue-on-error: true

    - name: Send Consolidated Email
      run: python email_sender.py
      continue-on-error: true
